// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: "category",
      label: "Module 1: Physical AI Foundations",
      items: [{ type: "autogenerated", dirName: "module-01-foundations" }],
    },
    {
      type: "category",
      label: "Module 2: Humanoid Hardware",
      items: [{ type: "autogenerated", dirName: "module-02-hardware" }],
    },
    {
      type: "category",
      label: "Module 3: Software & Control",
      items: [{ type: "autogenerated", dirName: "module-03-software" }],
    },
    {
      type: "category",
      label: "Module 4: Deployment & Safety",
      items: [{ type: "autogenerated", dirName: "module-04-deployment" }],
    },
  ],
};

export default sidebars;
