def format_for_channel(response: str, channel: str, ticket_id: str = "") -> str:
    if channel == "email":
        return f"""Dear Customer,

Thank you for reaching out to WHOOSH Support.

{response}

If you have further questions, please reply to this email.

Best regards,
WHOOSH AI Support Team
---
Ticket Reference: {ticket_id}
This response was generated by our AI assistant."""

    elif channel == "whatsapp":
        if len(response) > 300:
            response = response[:297] + "..."
        return f"{response}\n\nReply 'human' for live support."

    else:  # web_form
        return f"""{response}

---
Need more help? Reply to this message or visit our support portal.
Ticket: {ticket_id}"""
